baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'bandSite SessionS'

disableKinds = ["taxonomy","term"]

[Params]
  release_types = ['Album', 'DVD', 'single']
  discoGs_token = 'GmkhrkUTjIATRAkDxmxcIrNJbGoUsnYjxCAyFPlm'

[menu]
[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 10
[[menu.main]]
  name = "Music"
  pageRef = "music"
  weight = 15
[[menu.main]]
  name = "Discography"
  pageRef = "discography"
  parent = "Music"
  weight = 16
[[menu.main]]
  name = "About"
  pageRef = "about"
  weight = 40
[[menu.main]]
  name = "Gallery"
  pageRef = "gallery"
  weight = 20
[[menu.main]]
  name = "Calendar"
  pageRef = "calendar"
  weight = 30

[frontmatter]
  date = [':filename', ':default']